### ISSUE TITLE
[Bug] Depends on old version of svelte-loader

### ISSUE THREAD

**Issue by mvolkmann** [storybookjs/addon-svelte-csf#28] opened 2021-05-24 17:54 UTC
### Describe the bug

This depends on version 2.9.1 of svelte-loader, but svelte-kit depends on version 3.1.1.
The result is an "unable to resolve dependency tree" error when doing an `npm install` in a svelte-kit project.

**Comment by j3rem1e** [comment] 2021-05-26 18:32
The dep should be upgraded, but I don't understand why I can't reproduce this issue locally

**Comment by mvolkmann** [comment] 2021-05-26 18:56
@j3rem1e Try the steps I documented here: https://github.com/storybookjs/storybook/issues/15037

**Comment by mrmikardo** [comment] 2021-11-09 12:15
What's the latest on this issue? I can take a look, if that's helpful.

**Comment by mvolkmann** [comment] 2021-11-09 12:45
I tried this again today. When I follow the steps in the link above and then enter "npm run storybook" I get the following:

ERR! Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/mark/tmp/storybook-issue/.storybook/main.js from /Users/mark/tmp/storybook-issue/node_modules/@storybook/core-common/dist/cjs/utils/interpret-require.js not supported.
ERR! main.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
ERR! Instead rename main.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/mark/tmp/storybook-issue/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

**Comment by ChristianSch** [comment] 2022-01-29 18:03
Here's how to get it to work:  https://github.com/storybookjs/storybook/issues/15675#issuecomment-930143142

**Comment by j3rem1e** [comment] 2022-04-08 19:55
Fixed in 2.0.1

**Closed by j3rem1e** 2022-04-08 19:55 UTC
Labels: bug
