### ISSUE TITLE
[Bug] Cannot read property '__docgen' of undefined

### ISSUE THREAD

**Issue by frederikhors** [storybookjs/addon-svelte-csf#15] opened 2021-03-29 17:50 UTC
Using the code below throws this error:

`Cannot read property '__docgen' of undefined`

```svelte
<script lang="ts">
  import { Meta, Story, Template } from "@storybook/addon-svelte-csf";
</script>

<Meta title="Templates" />

<Template id="myTemplate" let:text>
  <div>Template 1 {text}</div>
</Template>

<Story
  id="s1"
  template="myTemplate"
  name="Story with myTemplate"
  args={{ text: "story1" }}
/>
```

Why?

**Comment by j3rem1e** [comment] 2021-03-29 18:11
I didn't reproduce it. Do you have a repo where I can check this bug ?

**Comment by alexanderniebuhr** [comment] 2021-03-29 19:06
have this too.
It was working with component prop on meta tag, but can be a false positive here since I have many issues with my setup

`<Meta title="Templates" component={} />`

**Comment by j3rem1e** [comment] 2021-03-29 19:36
It's not valid to have an null component in <Meta/>, but I can make the message more friendly.

**Comment by j3rem1e** [comment] 2021-03-29 20:30
Closing the issue as it's not related to this addon.

**Closed by j3rem1e** 2021-03-29 20:30 UTC
Labels: bug
