### ISSUE TITLE
TypeScript and Preprocessors support

### ISSUE THREAD

**Issue by engineforce** [storybookjs/addon-svelte-csf#4] opened 2021-03-10 00:46 UTC
### Describe the bug

Trying to use TypeScript in the stories.svelte caused error: `ParseError: Unexpected token`

``` 
<script lang="ts">
  import type { IRoute } from './IRoute';

  const ROUTES: IRoute[] = [
    {
      url: '/',
      title: 'Home',
    },
   ...
  ]

</script>
```

### Expected behavior

TypeScript should work using svelte preprocessor: https://svelte.dev/docs#svelte_preprocess

### Screenshots and/or logs

```
WARNING in ./src/modules/presentational/components/nav-bar2/NavBar2.stories.svelte
Module build failed (from ./node_modules/@storybook/addon-svelte-csf/dist/parser/svelte-stories-loader.js):
ParseError: Unexpected token
    at error (/Users/pli/my/git/engineforce/super-core/clients/boson/node_modules/svelte/compiler.js:16752:20)
    at Parser$1.error (/Users/pli/my/git/engineforce/super-core/clients/boson/node_modules/svelte/compiler.js:16828:10)
    at Parser$1.acorn_error (/Users/pli/my/git/engineforce/super-core/clients/boson/node_modules/svelte/compiler.js:16822:15)
    at Object.read_script [as read] (/Users/pli/my/git/engineforce/super-core/clients/boson/node_modules/svelte/compiler.js:7501:17)
    at tag (/Users/pli/my/git/engineforce/super-core/clients/boson/node_modules/svelte/compiler.js:15887:34)
    at new Parser$1 (/Users/pli/my/git/engineforce/super-core/clients/boson/node_modules/svelte/compiler.js:16787:22)
    at parse$3 (/Users/pli/my/git/engineforce/super-core/clients/boson/node_modules/svelte/compiler.js:16919:21)
    at Object.compile (/Users/pli/my/git/engineforce/super-core/clients/boson/node_modules/svelte/compiler.js:29918:18)
    at extractStories (/Users/pli/my/git/engineforce/super-core/clients/boson/node_modules/@storybook/addon-svelte-csf/dist/parser/extract-stories.js:49:32)
    at Object.transformSvelteStories (/Users/pli/my/git/engineforce/super-core/clients/boson/node_modules/@storybook/addon-svelte-csf/dist/parser/svelte-stories-loader.js:64:52)
 @ \.)(?=.)[^/]*?\.stories\.(js|jsx|ts|tsx|svelte))$ (./src sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(js|jsx|ts|tsx|svelte))$) ./modules/presentational/components/nav-bar2/NavBar2.stories.svelte
 @ ./.storybook/generated-stories-entry.js
```

### Environment

 - OS: MacOS Catalina 10.15.7
 - Node.js version: v12.13.1
 - NPM version: 6.12.1
 - svelte@3.35.0
 - @storybook/svelte@6.1.21
 - @storybook/addon-svelte-csf@1.0.0

**Comment by j3rem1e** [comment] 2021-03-10 11:56
I didn't think TypeScript/Preprocessor supports is important for stories, but I'll try to add it soon :smile:

It will reuse the configuration of storybook, inside `main.js` in `svelteOptions.preprocessor`

**Comment by mpeg** [comment] 2021-03-21 15:47
A problem with the lack of typescript support is that it also won't automatically detect props/events/slots/etc on typescript components, not just that the stories themselves can't be written in TS

I think it would be a great addition to this addon

**Comment by Nick-Mazuk** [comment] 2021-03-30 17:20
I second mpeg's observation. As soon as you add a single TypeScript definition, props/slots etc. aren't automatically detected.

**Comment by j3rem1e** [comment] 2021-03-30 18:51
I am waiting for Storybook v6.2 before adding this feature.

That's said, vscode check/autocompletion is not related to this issue. the vscode svelte plugin supports typescript checking without explicitly configuring a preprocessor.

**Comment by jesperp** [comment] 2021-06-26 15:45
Was just searching for TS support in svelte native format but ending up here. But now I also learned why some events/slots don't show up in SB 😄
Any news on this? 😊

**Comment by benbender** [comment] 2021-07-22 05:00
@j3rem1e any news on this one? Don't want to be pushy, but as ts-support is maturing in svelte, I would like to argue that this missing feature breaks the promise of "native" stories in storybook for svelte in a way. And (as in my case) it would be very convenient, to be able to write ts through the whole codebase and don't have to think about the context :) Thanks for your efforts!

**Comment by iva2k** [comment] 2021-10-21 04:37
Storybook is great and Svelte+Storybook+Typescript could be a very potent combination.

I'm using this workaround in .storybook/main.js to use Typescript components while the issue is being fixed:
```js
module.exports = {
  webpackFinal: async (config) => {
    const svelteLoader = config.module.rules.find( (r) => r.loader && r.loader.includes('svelte-loader'))
    svelteLoader.options.preprocess = require('svelte-preprocess')()
    return config
  },
  ...
};

```

**Comment by aberndtiteratec** [comment] 2021-12-07 10:26
> Storybook is great and Svelte+Storybook+Typescript could be a very potent combination.
> 
> I'm using this workaround in .storybook/main.js to use Typescript components while the issue is being fixed:
> 
> ```js
> module.exports = {
>   webpackFinal: async (config) => {
>     const svelteLoader = config.module.rules.find( (r) => r.loader && r.loader.includes('svelte-loader'))
>     svelteLoader.options.preprocess = require('svelte-preprocess')()
>     return config
>   },
>   ...
> };
> ```

Was anyone able to make it work with vite aswell?

**Comment by blindfish3** [comment] 2022-01-19 09:53
> Was anyone able to make it work with vite aswell?

I'm still working on it; but this runs OK (so far: I only have a skeleton project with no vendor imports):

<small>./storybook/main.js</small>
```js 
module.exports = {
	stories: ['../src/**/*.stories.@(js|jsx|ts|tsx|svelte)'],
	addons: ['@storybook/addon-links', '@storybook/addon-essentials', '@storybook/addon-svelte-csf'],
	framework: '@storybook/svelte',
	core: { builder: 'storybook-builder-vite' },
	async viteFinal(config, { configType }) {
		config.preprocess = preprocess({
			scss: {
				prependData: "@import './static/style.scss';"
			}
		});
		return config;
	}
};
```
I've seen examples where you handle preprocess like this:
```
svelteOptions: {
		"preprocess": import("../svelte.config.js").preprocess
	},
```
...but I couldn't get that to work; so I'm currently duplicating the config :/

I also had issues related to module imports.  To get around that I added ./storybook/package.json:
`{ "type": "commonjs" }`

Storybook seems to run fine with my TS components and my scss is processed correctly; but at the moment the Docs > code view sometimes shows `<Proxy<RenderContext>` instead of the component's tag.

**Comment by benmccann** [comment] 2022-07-06 18:07
I'm not sure how the various repos fit together, but I sent a fix for this in `builder-vite`: https://github.com/storybookjs/builder-vite/pull/428

**Comment by carusog** [comment] 2022-08-11 15:34
I set up a [fresh-install repo](https://github.com/carusog/svelte-tailwind-storybook) with a simple TypeScript component.
You can find 2 `FIXME` tasks in the code that highlight the issues.

I hope it can be useful to test this issue out.

The only two issues are currently:
1. TypeScript components are not supported. 
2. OT: Unresolved alias imports. I.E. trying to import components from ($lib/etc…) doesn't work.

Is there anything else we can do to help with this? More than happy to help.

**Comment by AcePetrucci** [comment] 2022-09-02 00:52
Any planned fixes for the two issues @carusog brought up?

**Comment by carusog** [comment] 2022-09-07 09:48
As a temporary workaround, I've set up my `main.cjs` file as follow:

```javascript
const sveltePreprocess = require('svelte-preprocess');
const path = require('path');

module.exports = {
	stories: [
		'../src/**/*.stories.mdx',
		'../src/**/*.stories.@(js|jsx|ts|tsx|svelte)'
	],
	addons: [
		'@storybook/addon-links',
		'@storybook/addon-essentials',
		'@storybook/addon-interactions',
		'@storybook/addon-svelte-csf'
	],
	framework: '@storybook/svelte',
	core: {
		builder: '@storybook/builder-vite'
	},
	svelteOptions: {
		preprocess: [
			sveltePreprocess({
				postcss: true // (1)
			})
		]
	},
	features: {
		storyStoreV7: false
	},
	async viteFinal(config, { configType }) { // (2)
		/** @type {import('vite').UserConfig} */
		return {
			...config,
			resolve: {
				alias: [
					{
						find: '$lib',
						replacement: path.resolve(__dirname, '../src/lib')
					},
				]
			},
		};
	}
};
```

Notice that I am:

1. duplicating Svelte options in here 🤷🏻‍♂️
2. duplicating (since Svelte itself is supposed to do so already) aliases in here as well

I am far away to be an expert, but I suspect this may be an issue with Vite interoperability features between CommonJS files and ES6 Modules files.

FYI @AcePetrucci

**Comment by AcePetrucci** [comment] 2022-09-07 10:48
In the end I had to give up on Svelte and SvelteKit for now since there's still so many issues trying to make them work with type definitions, storybook and exporting the components as WebComponents. Truly a shame since like Svelte as library so much.

But before that I also got it working too, somewhat similar to how you did:

```js
const path = require('path');
const { loadConfigFromFile, mergeConfig } = require('vite');

module.exports = {
	stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx|svelte)'],
	addons: [
		'@storybook/addon-links',
		'@storybook/addon-essentials',
		'@storybook/addon-interactions',
		'@storybook/addon-svelte-csf'
	],
	framework: '@storybook/svelte',
	core: {
		builder: '@storybook/builder-vite'
	},
	svelteOptions: {
		preprocess: import('../svelte.config.js').then((module) => {
			return module.preprocess;
		})
	},
	features: {
		storyStoreV7: false
	},
	async viteFinal(config, { configType }) {
		const { config: userConfig } = await loadConfigFromFile(
			path.resolve(__dirname, '../vite.config.js')
		);

		const plugins = userConfig.plugins
			.flat(1)
			.filter(
				(p) => !p.name.startsWith('vite-plugin-svelte') || p.name === 'vite-plugin-svelte-kit'
			);

		return mergeConfig(config, {
			...userConfig,
			plugins
		});
	}
};
```

I hope that can help anyone on the same boat

**Comment by carusog** [comment] 2022-09-08 10:28
Thanks, @AcePetrucci, it looks like a more elegant solution. I'll give it a try later this week. 🙏

**Comment by ryu-man** [comment] 2023-01-07 13:51
Using typescript does not work in `.stories.svelte` with `@storybook/addon-svelte-csf@3.0.0-next.3` and `vitePreprocess` in storybook@7 `beta`
this is what prints on the console
```
WARN 🚨 Extraction error on src\stories\Button.stories.svelte: Unexpected token (5:10)
WARN 3:   import Button from "./Button.svelte";
WARN 4: 
WARN 5:   let value: string;
WARN               ^
WARN 6: </script>
WARN 7:
CompileError [ParseError]: Unexpected token
```

**Comment by JReinhold** [comment] 2023-01-10 13:59
@ryu-man is what you're experiencing the same as #88?

**Comment by ryu-man** [comment] 2023-01-10 14:03
Yes the same issue

**Comment by Tyneor** [comment] 2023-08-16 22:46
I started a fresh repo and I don't have any issues with typescript inside the .stories.svelte using the default configuration.
I think this is fixed ?

**Comment by JReinhold** [comment] 2023-08-21 11:57
You might be right @Tyneor, I'll close this. If anyone is still experiencing this with the latest versions of packages, feel free to write again with a link to a reproduction.

**Closed by JReinhold** 2023-08-21 11:57 UTC
Labels: bug
