### ISSUE TITLE
Svelte 5 CSF Story and `play` function not found when running stories via Vitest

### ISSUE THREAD

**Issue by ndom91** [storybookjs/addon-svelte-csf#239] opened 2024-11-28 17:48 UTC
We've got the vitest experimental testing addon all setup and our stories run when executing `vitest run` and all the "does this component render" tests pass.

Now we've recently added a Svelte 5 CSF component [here](https://github.com/gitbutlerapp/gitbutler/blob/master/packages/ui/src/stories/button/Button.stories.svelte), and when I updated the `include` in [vitest.workspace.ts](https://github.com/gitbutlerapp/gitbutler/blob/master/packages/ui/vitest.workspace.ts) to include `.stories.svelte` files, it looks like Vitest doesn't pick up the CSF style story / play test in there.

![Image](https://github.com/user-attachments/assets/711e2156-65fd-4bed-aac3-9d595d207e62)

**Comment by xeho91** [comment] 2024-11-29 01:06
Portable stories required for experimental Vitest integration isn't there yet _(for this addon)_.
Is on the way, and you can track the progress in #213.

**Comment by JReinhold** [comment] 2024-11-29 17:17
Closing as duplicate of #213

**Closed** 2024-11-29 17:17 UTC
